owner: srdno
repo: status

sites:
  - name: Balise
    url: https://balise.no
  - name: SRD
    url: https://srd.no
  - name: GH1
    check: "tcp-ping"
    url: gh1.srd.no
    port: 22
  - name: GH2
    check: "tcp-ping"
    url: gh2.srd.no
    port: 22
  - name: GH3
    check: "tcp-ping"
    url: gh3.srd.no
    port: 22
  - name: GH4
    check: "tcp-ping"
    url: gh4.srd.no
    port: 22
assignees:
  - srdno
status-website:
  cname: status.srd.no
  logoUrl: https://srd.no/favicon.ico
  name: Status
  introTitle: "**Status**"
  customHeadHtml: "<script defer data-domain=\"status.srd.no\" src=\"https://analytics.srd.no/js/script.js\"></script>"
