# Change these first
owner: srdno # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: SRD
    url: https://srd.no
  - name: Balise
    url: https://balise.no
  #- name: IPv6 test
   # url: forwardemail.net
   # port: 80
   # check: "tcp-ping"
   # ipv6: true

status-website:
  cname: status.srd.no
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Status**"
  # introMessage:
  navbar:
    - title: Status
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
